name: Actualizar Playlist IPTV

on:
  schedule:
    - cron: '0 */23 * * *'  # Ejecuta cada 23 horas
  workflow_dispatch:       # Permite ejecuci칩n manual

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar requests
      run: pip install requests

    - name: Ejecutar script de actualizaci칩n
      run: python update_playlist.py

    - name: Commit y push si hay cambios
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist.m3u
        if ! git diff --cached --quiet; then
          git commit -m "Actualizaci칩n autom치tica de playlist"
          git push
        else
          echo "No hay cambios para commitear"
        fi
